version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dollar-price-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dollar-price-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dollar-price-frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - dollar-price-network

networks:
  dollar-price-network:
    driver: bridge

volumes:
  postgres_data: 